---

- name: Create VirtualBMC directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items:
    - "{{ working_dir }}/virtualbmc"
    - "{{ working_dir }}/virtualbmc/vbmc"
    - "{{ working_dir }}/virtualbmc/vbmc/conf"
    - "{{ working_dir }}/virtualbmc/vbmc/log"
    - "{{ working_dir }}/virtualbmc/sushy-tools"
  become: true

- name: Create VirtualBMC configuration file
  copy:
    mode: 0750
    dest: "{{ working_dir }}/virtualbmc/vbmc/virtualbmc.conf"
    content: |
      [default]
      config_dir=/root/.vbmc/conf/
      [log]
      logfile=/root/.vbmc/log/virtualbmc.log
      debug=True
      [ipmi]
      session_timout=20
  become: true

- name: get virthost non_root_user userid
  command: id -u {{ non_root_user }}
  register: non_root_user_uid

- name: set fact on non_root_user_uid
  set_fact:
    non_root_user_uid: "{{ non_root_user_uid.stdout }}"

# The first network defined with an address will be used for vbmc access.
- name: set vbmc address if there is a (nat) network defined with an address
  set_fact:
    vbmc_address: "{{ networks|selectattr('address_v4', 'defined')|map(attribute='address_v4')|list|first }}"
  when: networks|selectattr('address_v4', 'defined')|map(attribute='name')|list|length > 0

# The connection uri is slightly different when using qemu:///system
# and requires the root user.
- name: set qemu uri for qemu:///system usage
  set_fact:
    vbmc_libvirt_uri: "qemu+ssh://root@{{ vbmc_address | ipwrap }}/system?&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1"
  when: libvirt_uri == "qemu:///system"

- name: set qemu uri for qemu:///session usage
  set_fact:
    vbmc_libvirt_uri: "qemu+ssh://{{ non_root_user }}@{{ vbmc_address | ipwrap }}/session?socket=/run/user/{{ non_root_user_uid }}/libvirt/libvirt-sock&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1"
  when: vbmc_libvirt_uri is not defined

- name: Create VirtualBMC directories
  file:
    path: "{{ working_dir }}/virtualbmc/vbmc/conf/{{ item.name }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items: "{{ vm_nodes }}"
  become: true

- name: Create the Virtual BMCs
  copy:
    mode: 0750
    dest: "{{ working_dir }}/virtualbmc/vbmc/conf/{{ item.name }}/config"
    content: |
      [VirtualBMC]
      username = admin
      password = password
      domain_name = {{ item.name }}
      libvirt_uri = {{ vbmc_libvirt_uri }}
      address = ::
      active = True
      port = {{ item.virtualbmc_port }}
  with_items: "{{ vm_nodes }}"
  become: true

- name: Create the Redfish Virtual BMCs
  copy:
    mode: 0750
    dest: "{{ working_dir }}/virtualbmc/sushy-tools/conf.py"
    content: |
      SUSHY_EMULATOR_LIBVIRT_URI = "{{ vbmc_libvirt_uri }}"
  become: true
