non_root_user: "{{ lookup('env', 'USER') }}"

# base domain to use
cluster_domain: "{{ lookup('env', 'CLUSTER_DOMAIN') | default('ostest.test.metalkube.org', true) }}"

# allow the nic model to be overridden
libvirt_nic_model: virtio

# These defaults are used if there are no flavor-specific
# overrides configured.
default_disk: 50
default_memory: 8192
default_vcpu: 4
num_nodes: 2
extradisks: false
virtualbmc_base_port: 6230
flavors:
  node:
    memory: '{{node_memory|default(default_memory)}}'
    disk: '{{node_disk|default(default_disk)}}'
    vcpu: '{{node_vcpu|default(default_vcpu)}}'
    extradisks: '{{extradisks|bool}}'

# An optional prefix for node names
ironic_prefix: ""

baremetal_network_cidr_v4: "{{ lookup('env', 'EXTERNAL_SUBNET_V4') | default('192.168.111.0/24', true) }}"
baremetal_network_cidr_v6: "{{ lookup('env', 'EXTERNAL_SUBNET_V6') | default('fd55::/64', true) }}"

# Set this to `false` if you don't want your vms
# to have a VNC console available.
enable_vnc_console: true

# Path for volume storage
libvirt_volume_path: "{{ working_dir }}/pool"

# These ensure we're using privileged virt, so VMs persist over reboot
libvirt_uri: qemu:///system
ssh_user: root

# Describe our virtual networks.  These networks will be attached to
# the vm nodes in the order in which they are defined with the following caveats:
#   *  The first bridge network defined will be used for pxe booting
manage_baremetal: 'y'
networks:
  - name: provisioning
    bridge: provisioning
    forward_mode: bridge
  - name: baremetal
    bridge: baremetal
    forward_mode: "{% if manage_baremetal == 'y' %}nat{% else %}bridge{% endif %}"
    address_v4: "{{ baremetal_network_cidr_v4|nthhost(1) }}"
    netmask_v4: "{{ baremetal_network_cidr_v4|ipaddr('netmask') }}"
    dhcp_range_v4:
      - "{{ baremetal_network_cidr_v4|nthhost(20) }}"
      - "{{ baremetal_network_cidr_v4|nthhost(60) }}"
    address_v6: "{{ baremetal_network_cidr_v6|nthhost(1) }}"
    prefix_v6: "{{ baremetal_network_cidr_v6|ipaddr('prefix') }}"
    dhcp_range_v6:
      - "{{ baremetal_network_cidr_v6|nthhost(20) }}"
      - "{{ baremetal_network_cidr_v6|nthhost(60) }}"
    nat_port_range:
      - 1024
      - 65535
    domain: "{{ cluster_domain }}"
    dns:
      hosts: "{{dns_extrahosts | default([])}}"
      forwarders:
        - domain: "apps.{{ cluster_domain }}"
          addr: "127.0.0.1"
